### ISSUE TITLE
Import or add css 

### ISSUE THREAD

**Issue by Hahkarthick** [crabbly/Print.js#51]
How can i add or import css . I used media query but it wont take

**Comment by antoniorequenalorente** [comment]
I also need to add my custom css and I don't know how to do it

**Comment by crabbly** [comment]
Hey @antoniorequenalorente @Hahkarthick , what exactly are you guys trying to style?

**Comment by Hahkarthick** [comment]
@crabbly We actually need  is to add custom css file while print .while printing a container or page it grabs the content not alignment and other styles like(color , padding ,margin, etc....).hope if its fix it would best for  color prints also

**Comment by crabbly** [comment]
@Hahkarthick , I'm still confused here. Do you want to add custom css on the fly, when printing?
Sounds like all you need is a CSS media query:

```
@media print { 
   #myDivContainer { margin: 5px; } 
}
```

**Comment by crabbly** [comment]
CSS media query should fix this issue. I'll close this now. Please open it again if necessary. Thx.

**Comment by thearabbit** [comment]
I base on `Meteor + Vue`.
I tried `@media print{}`, but still don't work.
