### ISSUE TITLE
Safari 14.1.1 not printing pdf

### ISSUE THREAD

**Issue by kristin-dev** [crabbly/Print.js#584]
The latest version of Safari is not printing using printjs. Working well on Chrome and Firefox, getting a blank screen for PDF in Safari. The second time we try printjs, a dialog comes up that says "This webpage is trying to print. Do you want to print this webpage?" <Cancel> <Print>
And then clicking <Print> and there's a blank screen as well.

**Comment by sakinobashi** [comment]
I'm having this issue as well. I'm assuming it's a Safari issue, rather than Print.js issue, but if there is any information regarding potential reasons for this to happen and / or workarounds to make it work, it would be most welcome.

**Comment by itdys** [comment]
I'm having this issue as well. I try to use PrintJs and print a PDF file in safari(14.1.2), but when I preview the print file in dialog, I got a empty page.

**Comment by wmattei** [comment]
This should have been fixed in this PR: https://github.com/crabbly/Print.js/pull/588

**Comment by Trimakas** [comment]
Odd in that this PR has never been merged.. so the issue unfortunately still exists..
